
[functions.process-enrollment]
enabled = true
verify_jwt = true
import_map = "./functions/process-enrollment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-enrollment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-enrollment/*.html" ]

[functions.document-checklist-crud]
enabled = true
verify_jwt = true
import_map = "./functions/document-checklist-crud/deno.json"
entrypoint = "./functions/document-checklist-crud/index.ts"

[functions.generate-enrollment-sheet]
enabled = true
verify_jwt = true
import_map = "./functions/generate-enrollment-sheet/import_map.json"
entrypoint = "./functions/generate-enrollment-sheet/index.ts"
